mldata/urls.py
from django.conf.urls import url

from views import main
from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^$', main.results, name='main page'),
	url(r'^index/$', main.results, name='results page'),
	url(r'^register/$', main.register, name='register page'),
	url(r'^forgot/$', main.forgot, name='forgot password page'),
	url(r'^change-password/(?P<email>[\w\.-]+@[\w\.-]+(\.[\w]+)+)/token/(?P<token>[-\w]+)/$', main.changepassword, name='change password page'),
	url(r'^verify-account/(?P<email>[\w\.-]+@[\w\.-]+(\.[\w]+)+)/token/(?P<token>[-\w]+)/$', main.verify, name='verify account page'),
	url(r'^login/$', auth_views.login,{'template_name': 'login.html'}, name='login page'),
	url(r'^logout/$', auth_views.logout, {'next_page': '/mldata/login/'}, name='logout page'),
]

verv/urls.py
import json
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponse

def handler400(request):
    return HttpResponse(json.dumps({"detail": "Bad request."}), content_type="application/json", status=400)

def handler403(request):
    return HttpResponse(json.dumps({"detail": "You do not have permission to perform this action."}), content_type="application/json", status=403)

def handler404(request):
    return HttpResponse(json.dumps({"detail": "Not found."}), content_type="application/json", status=404)

def handler500(request):
    return HttpResponse(json.dumps({"detail": "Internal server error."}), content_type="application/json", status=500)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app/', include('account.urls')),
    url(r'^mldata/', include('mldata.urls')),
    url(r'^api/v1/', include('plug.urls_api_v1')),
    url(r'^api/v1/', include('hub.urls_api_v1')),
    url(r'^api/v1/', include('account.urls_api_v1')),
]

hub/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from account.models import User

class Hub(models.Model):
	TYPE_TYPE = (
		('HUBV1', 'Hub V1 Prototype'),
		('HUBV2', 'Hub V2 Production'),
	)
	GROUP_TYPE = (
		('VERV', 'VERV'),
		('DOE', 'DOE'),
		('DEWA', 'DEWA'),
		('PTT', 'PTT'),
	)
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='hub_user',blank=True,null=True)
	serial_number = models.CharField(max_length=45,unique=True)
	mac_address = models.CharField(max_length=45,unique=True)
	activated = models.BooleanField(default=True)
	type = models.CharField(max_length=55,choices=TYPE_TYPE,default='HUBV1',)
	type_description = models.TextField(default='')
	group = models.CharField(max_length=55,choices=GROUP_TYPE,default='VERV',)
	group_description = models.TextField(default='')
	release_version = models.CharField(max_length=55)

	def __str__(self):
		return self.serial_number

mldata/forms/register.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.apps import apps
from rest_framework.validators import UniqueValidator

User = apps.get_model('account','User')

class RegisterForm(UserCreationForm):
    password1 = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254,help_text='Required. Inform a valid email address.',)
    first_name = forms.CharField(max_length=30,required=True, help_text='Required a valid first name.')
    last_name = forms.CharField(max_length=30,required=True)
    middle_name = forms.CharField(max_length=30,required=False)
    backup_email = forms.EmailField(max_length=254,help_text='Required. Inform a valid email address.',required=False)
    postcode = forms.CharField(max_length=30,required=False)
    address = forms.CharField(max_length=60,required=False)
    password2 = None

    class Meta:
        model = User
        fields = ('email','first_name','middle_name', 'last_name', 'backup_email', 'address', 'postcode', 'password1',)

mldata/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

mldata/templates/changepassword.html
{% extends 'base.html' %}
{% block content %}
    <div class="card p-2" style="max-width:350px;margin: 80px auto;">
        <form class="px-4 py-3" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control {% if form.password1.errors %} is-invalid{% endif %}" name="password1" id="password1" placeholder="Password">
                <div class="invalid-feedback">{{ form.password1.errors }}</div>
            </div>
            <button type="submit" class="btn btn-primary">Set new password</button>
        </form>
        <div class="dropdown-divider"></div>
        <div class="nav flex-column">
            <a class="underlineHover px-4 nav-link" href="{% url 'login page' %}">Back to login</a>
        </div>
    </div>
    {% include "modal.html" %}
{% endblock %}

mldata/templates/forgot.html
{% extends 'base.html' %}
{% block content %}
    <div class="card p-2" style="max-width:350px;margin: 80px auto;">
        <form class="px-4 py-3" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="email@example.com">
            </div>
            <button type="submit" class="btn btn-primary">Reset my password</button>
        </form>
        <div class="dropdown-divider"></div>
        <div class="nav flex-column">
            <a class="underlineHover px-4 nav-link" href="{% url 'login page' %}">Back to login</a>
        </div>
    </div>
    {% include "modal.html" %}
{% endblock %}

mldata/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="card p-2" style="max-width:350px;margin: 80px auto;">
        <form class="px-4 py-3" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" name="username" required id="email" placeholder="email@example.com">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" required id="password" placeholder="Password">
            </div>
            <input type="hidden" name="next" value="{% url 'results page' %}" />
            <button type="submit" class="btn btn-primary">Sign in</button>
        </form>
        <div class="dropdown-divider"></div>
        <div class="nav flex-column">
            <a class="underlineHover px-4 nav-link" href="{% url 'register page' %}">New around here? Sign up</a>
            <a class="underlineHover px-4 nav-link" href="{% url 'forgot password page' %}">Forgot password?</a>
        </div>
    </div>
    {% include "modal.html" %}
{% endblock %}

mldata/templates/modal.html
{% if messages %}
    {% for message in messages %}
        <div class="modal" tabindex="-1" role="dialog" id="messages-{{ message.tags }}">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ message.tags }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" target="#messages-{{ message.tags }}" onclick="goTo('{% url 'login page' %}')" >
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" onclick="goTo('{% url 'login page' %}')" data-dismiss="modal" target="#messages-{{ message.tags }}">Close</button>
                </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(window).on('load',function(){
                $('#messages-{{ message.tags }}').modal('show');
            });
            function goTo(link){
                window.location.assign(link);
            }
        </script>
    {% endfor %}
{% endif %}

mldata/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="card p-2" style="max-width:350px;margin: 80px auto;">
        <form class="px-4 py-3" id="registration_form" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="first_name">First Name</label>
                <input type="text" class="form-control {% if form.first_name.errors %} is-invalid{% endif %} " name="first_name" id="first_name" placeholder="Dan" {% if form.first_name.value %} value="{{form.first_name.value }}" {% endif %}>
                <div class="invalid-feedback">{{ form.first_name.errors }}</div>
            </div>
            <div class="form-group">
                <label for="last_name">Last Name</label>
                <input type="text" class="form-control {% if form.last_name.errors %} is-invalid{% endif %}" name="last_name" id="last_name" placeholder="Evans" {% if form.last_name.value %} value="{{form.last_name.value }}" {% endif %}>
                <div class="invalid-feedback">{{ form.last_name.errors }}</div>
            </div>
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control {% if form.email.errors %} is-invalid{% endif %}" name="email" id="email" placeholder="email@example.com" {% if form.email.value %} value="{{form.email.value }}" {% endif %}>
                <div class="invalid-feedback">{{ form.email.errors }}</div>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control {% if form.password1.errors %} is-invalid{% endif %}" name="password1" id="password1" placeholder="Password">
                <div class="invalid-feedback">{{ form.password1.errors }}</div>
            </div>
            <div class="form-group">
                <div class="g-recaptcha" data-sitekey="6LeA_60UAAAAAC5c32_Ms43N4RWvyCbM1wcQ6Ffv" name="g-recaptcha-response" style="transform: scale(0.94);transform-origin: left;"></div>
            </div>
            <button type="submit" class="btn btn-primary">Sign up</button>
        </form>
        <div class="dropdown-divider"></div>
        <div class="nav flex-column">
            <a class="underlineHover px-4 nav-link" href="{% url 'login page' %}">Back to login</a>
        </div>
        <script src="https://www.google.com/recaptcha/api.js" async defer></script>
        {% include "modal.html" %}
    </div>
{% endblock %}

mldata/templates/results.html
{% extends 'base.html' %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item my-2 my-lg-0">Welcome back {{user}}</li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item my-2 my-lg-0"><a class="nav-link" href="{% url 'logout page' %}"  role="button" >Logout</a></li>
    </ul>
</nav>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Brand
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for item in menu %}
                        {% ifchanged %}{% if not forloop.first %}<div class="dropdown-divider"></div>{% endif %}<a class="dropdown-item" href="#" onClick="get_param('brand','{{item.brand}}'); return false;">{{item.brand}}</a>{% endifchanged %}
                    {% endfor %}
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Appliance Type
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for item in menu %}
                        {% ifchanged %}{% if not forloop.first %}<div class="dropdown-divider"></div>{% endif %}<a class="dropdown-item" href="#" onClick="get_param('type','{{item.type}}'); return false;">{{item.get_type_display}}</a>{% endifchanged %}
                    {% endfor %}
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Appliance Age
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#" onClick="get_param('age','12'); return false;">New</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" onClick="get_param('age','24'); return false;">Mid</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" onClick="get_param('age','36'); return false;">Old</a>
                </div>
            </li>

        </ul>
        <form class="form-inline my-2 my-lg-0" method="get">
            <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>





<table class="table">
    <thead class="thead-inverse thead-dark text-center">
        <tr>
            <th>Link</th>
            <th>Duration Time</th>
            <th>Appliance Type</th>
            <th>Brand</th>
            <th>Model</th>
            <th>Age</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody class="text-center">
        {% for action in actions %}
            <tr>
                <td class="align-middle"><button type="button" class="btn btn-primary btn-sm">Download</button></td>
                <td class="align-middle">{{ action.get_duration}}</td>
                <td class="align-middle">{{ action.appliance.get_type_display }}</td>
                <td class="align-middle">{{ action.appliance.brand }}</td>
                <td class="align-middle">{{ action.appliance.model }}</td>
                <td class="align-middle">{{ action.appliance.age }}</td>
                <td class="align-middle">
                    {% for item,value in action.description.items %}
                        <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {{ item }} <span class="badge badge-primary badge-pill text-truncate" style="max-width: 100px;">{{value}}</span>
                            </li>
                        </ul>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>



{% if actions.has_other_pages %}
    <ul class="pagination justify-content-center">
        {% if actions.has_previous %}
            <li class="page-item"><a class="page-link" href="#" onClick="get_param('page','{{ actions.previous_page_number }}'); return false;">&laquo;</a></li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
        {% endif %}

        {% for i in actions.paginator.page_range %}
            {% if actions.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#" onClick="get_param('page','{{ i }}'); return false;">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if actions.has_next %}
            <li class="page-item"><a class="page-link" href="#" onClick="get_param('page','{{ actions.next_page_number }}'); return false;">&raquo;</a></li>
        {% else %}
            <li class="page-item disabled"><span class="page-link" >&raquo;</span></li>
        {% endif %}
    </ul>
{% endif %}

<script>
    function get_param(param,value){
        var url = new URL(window.location.href);
        url.searchParams.set(param, value);
        window.location.assign(url);
    }
</script>

{% endblock %}